name: belt_app
description: An app for image editing.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  freezed_annotation: ^2.2.0
  photo_manager: ^2.4.1
  path_provider: ^2.0.11
  camera: ^0.10.0+4
  photo_view: ^0.14.0
  provider: ^6.0.4
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
